const CLIPBOARD_ITEMS_STORAGE_KEY = 'clipboardItems';
const CLIPBOARD_ITEM_VALUE_MAX_LENGTH = 100;
const DEFAULT_CLIPBOARD_ITEM = {
  label: 'ID - Title',
  value: '[id] - [title]',
};

export {
  CLIPBOARD_ITEMS_STORAGE_KEY,
  CLIPBOARD_ITEM_VALUE_MAX_LENGTH,
  DEFAULT_CLIPBOARD_ITEM,
};
